<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <PropertyGroup>
    <AssemblyName>aod</AssemblyName>
    <RootNamespace>Ambermoon.Aon.Cli</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aon.Core\Aon.Core.csproj" />
  </ItemGroup>

</Project>
